"""adding first_km column at vehicles table

Revision ID: 11a86e76967a
Revises: f2a589d1a677
Create Date: 2025-06-22 18:21:41.015487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a86e76967a'
down_revision = 'f2a589d1a677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('shipment')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_km', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('first_km')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('shipment', ['shipment'], unique=True)

    # ### end Alembic commands ###
