"""empty message

Revision ID: 4e1cbdb9f052
Revises: 2ccd8a6549b4
Create Date: 2025-04-20 11:50:24.453097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e1cbdb9f052'
down_revision = '2ccd8a6549b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=50), nullable=True))
        batch_op.drop_column('pathname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pathname', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
