"""updating reports table

Revision ID: 6faeff254675
Revises: cbc1055a2fd3
Create Date: 2025-06-12 09:39:39.280054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6faeff254675'
down_revision = 'cbc1055a2fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fulfillment', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('fulfillment')

    # ### end Alembic commands ###
