"""update reports table

Revision ID: cbc1055a2fd3
Revises: 43fd91f6ea31
Create Date: 2025-06-12 09:05:44.709586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc1055a2fd3'
down_revision = '43fd91f6ea31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odometer', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('dispenser', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('dispenser')
        batch_op.drop_column('odometer')

    # ### end Alembic commands ###
