"""adding similarity column at Reports table

Revision ID: f2a589d1a677
Revises: 6faeff254675
Create Date: 2025-06-16 21:16:02.396806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a589d1a677'
down_revision = '6faeff254675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similarity', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('similarity')

    # ### end Alembic commands ###
